
Running tests... 
----------------------------------------------------------------------
 test_001 (test_api.TestBaidu) ... OK (6.237765)s
 test_002 (test_api.TestBaidu) ... ERROR (2.585187)s
 test_003 (test_api.TestBaidu) ... ERROR (0.000000)s

======================================================================
ERROR [2.585187s]: test_002 (test_api.TestBaidu)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\小米笔记本\Desktop\全篇\testcase\test_api.py", line 23, in test_002
    t = auto_post(url=url, data=data)
  File "C:\Users\小米笔记本\Desktop\全篇\common\requests_api.py", line 26, in auto_post
    return post_response.status_code, post_response.json()
  File "D:\办公软件\python\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\办公软件\python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\办公软件\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\办公软件\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

======================================================================
ERROR [0.000000s]: test_003 (test_api.TestBaidu)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\小米笔记本\Desktop\全篇\testcase\test_api.py", line 28, in test_003
    unittest.TestCase.fail()
TypeError: fail() missing 1 required positional argument: 'self'

----------------------------------------------------------------------
Ran 3 tests in 0:00:08

FAILED
 (Errors=2)

Generating HTML reports... 
